# GitLeaks configuration for detecting secrets in the codebase
[[rules]]
  description = "Generic secret"
  regex = '''(?i)(?:[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,})|(?:[A-Za-z0-9._%+-]{32,})|(?:[A-Za-z0-9]{40})|(?:[A-Za-z0-9]{64})'''
  tags = ["generic", "secret"]

[[rules]]
  description = "AWS Access Key"
  regex = '''(?i)(?:A3T[A-Z0-9]{16})|(?:AKIA[A-Z0-9]{16})|(?:ASIA[A-Z0-9]{16})'''
  tags = ["aws", "secret"]

[[rules]]
  description = "AWS Secret Key"
  regex = '''(?i)(?:[A-Za-z0-9/+=]{40})'''
  tags = ["aws", "secret"]

[[rules]]
  description = "Google Cloud Service Account Key"
  regex = '''(?i)(?:"type":\s*"service_account")'''
  tags = ["gcp", "secret"]

[[rules]]
  description = "Azure Service Principal Key"
  regex = '''(?i)(?:"client_secret":\s*")([A-Za-z0-9-._~+/=]{32,})'''
  tags = ["azure", "secret"]

[[rules]]
  description = "Heroku API Key"
  regex = '''(?i)(?:[A-Za-z0-9]{32})'''
  tags = ["heroku", "secret"]

[[rules]]
  description = "Stripe Secret Key"
  regex = '''(?i)(?:sk_live_[0-9a-zA-Z]{24})|(?:sk_test_[0-9a-zA-Z]{24})'''
  tags = ["stripe", "secret"]

[[rules]]
  description = "Twilio Auth Token"
  regex = '''(?i)(?:[A-Za-z0-9]{32})'''
  tags = ["twilio", "secret"]