name: "Set Docker image variables"
description: "Define Docker user, image name, and tag as environment variables"
runs:
  using: "composite"
  steps:
    - run: |
        echo "DOCKER_ACCOUNT=brgilsonsp" >> $GITHUB_ENV
        echo "IMAGE_NAME=projeto-devsecops-pipeline" >> $GITHUB_ENV
        echo "URL_DOCKER_HUB_REPO=https://hub.docker.com/repository/docker/brgilsonsp/projeto-devsecops-pipeline/general" >> $GITHUB_ENV
      shell: bash