name: "Set Docker image variables"
description: "Define Docker user, image name, and tag as environment variables"
runs:
  using: "composite"
  steps:
    - run: |
        echo "DOCKER_USER=brgilsonsp" >> $GITHUB_ENV
        echo "IMAGE_NAME=projeto-devsecops-pipeline" >> $GITHUB_ENV
      shell: bash