name: CI/CD Pipeline for Develop Branch

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check if develop is behind main
        run: |
          git fetch origin main
          behind_main=$(git rev-list --left-only --count HEAD...origin/main)
          if [ "$behind_main" -gt 0 ]; then
            echo "Branch is behind main. Please update your branch."
            exit 1
          fi
          echo "Branch is up to date with develop and main."

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'

      - name: Run Lint Checks
        working-directory: ./app
        run: mvn checkstyle:check

      - name: Run Unit Tests
        working-directory: ./app
        run: mvn test

      - name: Run Integration Tests
        working-directory: ./app
        run: mvn verify

      - name: Build Application
        working-directory: ./app
        run: mvn package

      - name: Set Docker image variables
        uses: ./.github/actions/vars-docker

      - name: Set Docker image tag
        run: echo "IMAGE_TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Build Docker Image
        run: |
          docker build -t ${{ env.IMAGE_NAME }} .

      - name: Push Docker Image
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker tag ${{ env.IMAGE_NAME }} ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}