name: CI/CD Pipeline for Main Branch

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Build with Maven
        working-directory: ./app
        run: mvn clean package --file pom.xml

      - name: Build Docker image
        run: |
          docker build -t myapp:latest .

      - name: Push Docker image to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker tag myapp:latest myusername/myapp:latest
          docker push myusername/myapp:latest

      - name: Deploy to Production
        run: |
          ssh user@your-server "docker pull myusername/myapp:latest && docker run -d -p 8080:8080 myusername/myapp:latest"