name: CI/CD Pipeline for Main Branch

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set pipelines variables
        uses: ./.github/actions/vars-pipe

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run Lint Checks
        working-directory: ./app
        run: |
          set +e
          mvn checkstyle:check
          status=$?
          if [ "$status" -ne 0 ]; then
            echo "Lint errors found."
            if [ "${BYPASS_LINT}" = "true" ]; then
              echo "Bypass lint is enabled. Continuing pipeline despite lint errors."
              exit 0
            else
              echo "Pipeline interrupted due to lint errors."
              exit 1
            fi
          fi
        env:
          BYPASS_LINT: ${{ env.BYPASS_LINT }}

      - name: Run Unit Tests
        working-directory: ./app
        run: mvn test

      - name: Build Application
        working-directory: ./app
        run: mvn package

      - name: Set Docker image variables
        uses: ./.github/actions/vars-docker

      - name: Set Docker image tag
        run: echo "IMAGE_TAG=v${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t ${{ env.IMAGE_NAME }} .

      - name: Push versioned Docker image
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker tag ${{ env.IMAGE_NAME }} ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          echo "Docker image pushed to: https://hub.docker.com/repositories/${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}"

      - name: Tag as latest and push
        run: |
          docker tag ${{ env.IMAGE_NAME }} ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest

      - name: Deploy to Production
        run: |
          ssh user@your-server "docker pull ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} && docker run -d -p 8080:8080 ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}"