name: CI for Feature Branches

on:
  push:
    branches:
      - 'feature/*'

jobs:
  feature-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Check if branch is behind develop or main
        run: |
          git fetch origin develop
          git fetch origin main
          behind_develop=$(git rev-list --left-only --count origin/develop...HEAD)
          behind_main=$(git rev-list --left-only --count origin/main...HEAD)
          branch_actual=$(git rev-parse --abbrev-ref HEAD)
          echo "Current branch: $branch_actual"
          echo "Behind develop: $behind_develop"
          echo "Behind main: $behind_main"
          if [ "$behind_develop" -gt 0 ]; then
            echo "Branch is behind develop. Please update your branch."
            exit 1
          fi
          if [ "$behind_main" -gt 0 ]; then
            echo "Branch is behind main. Please update your branch."
            exit 1
          fi
          echo "Branch is up to date with develop and main."

      - name: Run lint checks
        working-directory: ./app
        run: mvn checkstyle:check

      - name: Run unit tests
        working-directory: ./app
        run: mvn test

      - name: Run security scans
        working-directory: ./app
        run: |
          mvn org.owasp:dependency-check-maven:check
          gitleaks --path=. --config=security/gitleaks.toml --verbose

      - name: Build application
        working-directory: ./app
        run: mvn package